# Generated by Django 5.2.6 on 2025-09-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_handle', models.CharField(max_length=100)),
                ('wallet_address', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=9, max_digits=20)),
                ('signature', models.CharField(max_length=255, unique=True)),
                ('network', models.CharField(default='devnet', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
